---

- name: Create gedit user theme directory
  become: true
  become_user: "{{ user }}"
  ansible.builtin.file:
    path: "{{ gedit_user_theme_path }}"
    state: directory
    mode: "0755"

- name: Copy gedit theme
  become: true
  become_user: "{{ user }}"
  ansible.builtin.copy:
    src: "lavanda.xml"
    dest: "{{ gedit_user_theme_path }}/lavanda.xml"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_effective_group_id }}"
    mode: "0755"

- name: Configure gedit settings
  become: true
  become_user: "{{ user }}"
  loop: "{{ gedit_settings | dict2items }}"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value | string }}"

...
